name: Push-to-EC2
on:
    push:
        branches:
            - master
jobs:
    deploy:
        name: Deploy to EC2
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the files
              uses: actions/checkout@v4

            - name: Copy files backend with SSH
              uses: easingthemes/ssh-deploy@main
              env:
                  SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: './backend/*'
                  REMOTE_HOST: 'ec2-184-72-100-214.compute-1.amazonaws.com'
                  REMOTE_USER: 'ec2-user'
                  TARGET: '/home/ec2-user'
                  EXCLUDE: '/dist/, /node_modules/, **.env, rebuild_app.sh, watcher.sh, .git'

            - name: Build Backend
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - run: npm i
            - run: npm run build --if-present
            - run: npm run start

            # - name: Build Frontend
            #   uses: actions/setup-node@v4
            #   env:
            #       ARGS: '-rltgoDzvO --delete'
            #       SOURCE: './frontend/*'
            #       REMOTE_HOST: 'ec2-184-72-100-214.compute-1.amazonaws.com'
            #       REMOTE_USER: 'ec2-user'
            #       TARGET: '/home/ec2-user'
            #       EXCLUDE: '/dist/, /node_modules/, **.env, rebuild_app.sh, watcher.sh, .git'

            # - run: npm i
            # - run: npm run build --if-present
            # - run: npm run start
